### PR TITLE
dataset(asl_lex): add new dataset

### LINKED ISSUE #31: dataset(asllex): add asl lex dataset
https://asl-lex.org/download.html

### PR DESCRIPTION
**Pull request by AmitMY**
Initial dataset only includes the rows for metadata, no videos since they are not available to download trivially
fixes #31

### CODE REVIEW

**Comment by bricksdont** [comment]
Doing this:

```python
config = SignDatasetConfig(name="only-annotations", version="3.0.0", include_video=False)
asl_lex = tfds.load(name='asl_lex', builder_kwargs=dict(config=config))
```

I run into an error:

```python
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/dist-packages/sign_language_datasets/datasets/asl_lex/data-key.csv'


The above exception was the direct cause of the following exception:

FileNotFoundError                         Traceback (most recent call last)

[/usr/local/lib/python3.9/dist-packages/tensorflow_datasets/core/utils/py_utils.py](https://localhost:8080/#) in reraise(e, prefix, suffix)
    382     else:
    383       exception = RuntimeError(f'{type(e).__name__}: {msg}')
--> 384     raise exception from e
    385   # Otherwise, modify the exception in-place
    386   elif len(e.args) <= 1:

FileNotFoundError: Failed to construct dataset asl_lex: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/dist-packages/sign_language_datasets/datasets/asl_lex/data-key.csv'
```

looks like it has to do with wich additional files (= package data) are distributed in `setup.py`, but I did not find the issue yet

**Comment by bricksdont** [comment]
... the problem is that https://github.com/sign-language-processing/datasets/blob/asl-lex/MANIFEST.in does not cover CSV files

**Comment by AmitMY** [comment]
Nice catch! Added that

**Comment by bricksdont** [comment]
Now a recent change to pose-format leads to this:

```python
---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-2-842dd6697810>](https://localhost:8080/#) in <module>
      1 import tensorflow_datasets as tfds
----> 2 import sign_language_datasets.datasets
      3 from sign_language_datasets.datasets.config import SignDatasetConfig
      4 
      5 import itertools

6 frames

[/usr/local/lib/python3.9/dist-packages/pose_format/pose.py](https://localhost:8080/#) in <module>
      5 import numpy.ma as ma
      6 
----> 7 from pose_format.numpy import NumPyPoseBody
      8 from pose_format.pose_body import PoseBody
      9 from pose_format.pose_header import PoseHeader, PoseHeaderDimensions, PoseNormalizationInfo, PoseHeaderComponent

ModuleNotFoundError: No module named 'pose_format.numpy'
```

**Comment by AmitMY** [comment]
I think you might have a local installation of `pose_format`.
Here is a reproduction: https://colab.research.google.com/drive/1BSPMMUaJre5U3XO2FKN5BzwaQe--LFY9?usp=sharing
It doesn't happen if installed from pip

**Comment by bricksdont** [comment]
ah yes, but it happens if I do this:

```python
import sign_language_datasets.datasets
```

am I not supposed to do this anymore? I remember this was necessary for TFDS to recognize local datasets

**Review by bricksdont — APPROVED** [review]
I now tested the code with the newest `pose-format` version, the code works now and everything looks good to me.

Minor: please bump the minor library version

**Pull request merged**
